AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Enviornment:
    Type: String
    Default: Dev

Globals:
  Function:
    Runtime: python3.8
    CodeUri: lambdas/
    Enviornment:
      Variables:
        AccountId: !Ref AWS::AccountId

Resources:
  NewFunction:
    Properties:
      Timeout: 30
      Handler: lambda._handler
    Type: AWS::Serverless::Function


